### PR TITLE
Fixed program crash on negative input in fak()

### PR DESCRIPTION
**Pull request by kloppstock**

### CODE REVIEW

**Comment by fer-rum** [comment]
Iirc, you tell your students early on that they have to always sanitize their inputs. It should therefore be done so in the slides (at least in form of a commentary hint like `// Sanitize input...`).
Why do I bother? Because I have dealt with a lot of real-life code in the recent months and small things like these can catch bugs so much earlier and faster. Especially when dealing with pointers.

So :+1:

**Comment by Lodifice** [comment]
First of all thanks for your feedback. @fer-rum wer aren't talking about the slides here, but about the solutions of the exercises. Unfortunately, their code quality is pretty bad, they contain errors and countradict our style guidelines. So I'd say they need a major rework and any help is appreciated :+1: 

However, in this example, your solution is wrong: 0! would be 1. So I suggest changing the `if (n == 1)` to `if (n <= 1)`. Would you also improve the Fibonacci example (experts' task)? We check the value in the main function which isn't best practice, either.

**Comment by uncomputable** [comment]
I completely agree that a function should perform all the checks of its arguments, but this Fibonacci function is problematic:

`exit()` isn't covered before the 6th presentation, making early program termination on errors impossible. So we either need to implement the bidirectional sequence _(more work)_, or return the `double` NaN on a negative input _(kind of a hack)_, or simply leave it as it is with the if check in `main`.

**Comment by kloppstock** [comment]
The Fibonacci function already handles illegal (although it isn't pretty). It returns n if `n < 1`.
The Bug mentioned above should be fixed now.

**Pull request merged**
